language: java

before_install:
    - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.6-bin.tar.gz
    - tar -xzvf apache-ant-1.10.6-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH
    - echo $(ant -version)
    
jdk:
  - openjdk11

script: ant build